package com.exam.pojo;
// Generated Oct 2, 2016 10:27:00 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Flat generated by hbm2java
 */
public class Flat  implements java.io.Serializable {


     private String flatNo;
     private String flatName;
     private String bedRoom;
     private String drawingRoom;
     private String kitchenRoom;
     private String washRoom;
     private String atachBathRoom;
     private String belcony;
     private String flatSize;
     private String parking;
     private String flatImage;
     private String roomImage;
     private String othersImage;
     private Set saleses = new HashSet(0);

    public Flat() {
    }

	
    public Flat(String flatNo) {
        this.flatNo = flatNo;
    }
    public Flat(String flatNo, String flatName, String bedRoom, String drawingRoom, String kitchenRoom, String washRoom, String atachBathRoom, String belcony, String flatSize, String parking, String flatImage, String roomImage, String othersImage, Set saleses) {
       this.flatNo = flatNo;
       this.flatName = flatName;
       this.bedRoom = bedRoom;
       this.drawingRoom = drawingRoom;
       this.kitchenRoom = kitchenRoom;
       this.washRoom = washRoom;
       this.atachBathRoom = atachBathRoom;
       this.belcony = belcony;
       this.flatSize = flatSize;
       this.parking = parking;
       this.flatImage = flatImage;
       this.roomImage = roomImage;
       this.othersImage = othersImage;
       this.saleses = saleses;
    }
   
    public String getFlatNo() {
        return this.flatNo;
    }
    
    public void setFlatNo(String flatNo) {
        this.flatNo = flatNo;
    }
    public String getFlatName() {
        return this.flatName;
    }
    
    public void setFlatName(String flatName) {
        this.flatName = flatName;
    }
    public String getBedRoom() {
        return this.bedRoom;
    }
    
    public void setBedRoom(String bedRoom) {
        this.bedRoom = bedRoom;
    }
    public String getDrawingRoom() {
        return this.drawingRoom;
    }
    
    public void setDrawingRoom(String drawingRoom) {
        this.drawingRoom = drawingRoom;
    }
    public String getKitchenRoom() {
        return this.kitchenRoom;
    }
    
    public void setKitchenRoom(String kitchenRoom) {
        this.kitchenRoom = kitchenRoom;
    }
    public String getWashRoom() {
        return this.washRoom;
    }
    
    public void setWashRoom(String washRoom) {
        this.washRoom = washRoom;
    }
    public String getAtachBathRoom() {
        return this.atachBathRoom;
    }
    
    public void setAtachBathRoom(String atachBathRoom) {
        this.atachBathRoom = atachBathRoom;
    }
    public String getBelcony() {
        return this.belcony;
    }
    
    public void setBelcony(String belcony) {
        this.belcony = belcony;
    }
    public String getFlatSize() {
        return this.flatSize;
    }
    
    public void setFlatSize(String flatSize) {
        this.flatSize = flatSize;
    }
    public String getParking() {
        return this.parking;
    }
    
    public void setParking(String parking) {
        this.parking = parking;
    }
    public String getFlatImage() {
        return this.flatImage;
    }
    
    public void setFlatImage(String flatImage) {
        this.flatImage = flatImage;
    }
    public String getRoomImage() {
        return this.roomImage;
    }
    
    public void setRoomImage(String roomImage) {
        this.roomImage = roomImage;
    }
    public String getOthersImage() {
        return this.othersImage;
    }
    
    public void setOthersImage(String othersImage) {
        this.othersImage = othersImage;
    }
    public Set getSaleses() {
        return this.saleses;
    }
    
    public void setSaleses(Set saleses) {
        this.saleses = saleses;
    }




}


