package com.exam.pojo;
// Generated Oct 2, 2016 10:27:00 PM by Hibernate Tools 4.3.1



/**
 * Flat2 generated by hbm2java
 */
public class Flat2  implements java.io.Serializable {


     private Integer flatId;
     private String title;
     private String location;
     private String details;
     private String city;
     private String collection;
     private String size;
     private Integer bedrooms;
     private Integer bathrooms;
     private String image;

    public Flat2() {
    }

    public Flat2(Integer flatId, String title, String location, String details, String city, String collection, String size, Integer bedrooms, Integer bathrooms, String image) {
        this.flatId = flatId;
        this.title = title;
        this.location = location;
        this.details = details;
        this.city = city;
        this.collection = collection;
        this.size = size;
        this.bedrooms = bedrooms;
        this.bathrooms = bathrooms;
        this.image = image;
    }

    public Flat2(Integer flatId, String title, String location, String details, String image) {
        this.flatId = flatId;
        this.title = title;
        this.location = location;
        this.details = details;
        this.image = image;
    }

    public Flat2(String title, String location, String details, String city, String collection, String size, Integer bedrooms, Integer bathrooms, String image) {
       this.title = title;
       this.location = location;
       this.details = details;
       this.city = city;
       this.collection = collection;
       this.size = size;
       this.bedrooms = bedrooms;
       this.bathrooms = bathrooms;
       this.image = image;
    }
   
    public Integer getFlatId() {
        return this.flatId;
    }
    
    public void setFlatId(Integer flatId) {
        this.flatId = flatId;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }
    public String getDetails() {
        return this.details;
    }
    
    public void setDetails(String details) {
        this.details = details;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getCollection() {
        return this.collection;
    }
    
    public void setCollection(String collection) {
        this.collection = collection;
    }
    public String getSize() {
        return this.size;
    }
    
    public void setSize(String size) {
        this.size = size;
    }
    public Integer getBedrooms() {
        return this.bedrooms;
    }
    
    public void setBedrooms(Integer bedrooms) {
        this.bedrooms = bedrooms;
    }
    public Integer getBathrooms() {
        return this.bathrooms;
    }
    
    public void setBathrooms(Integer bathrooms) {
        this.bathrooms = bathrooms;
    }
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }




}


