package com.exam.pojo;
// Generated Oct 2, 2016 10:27:00 PM by Hibernate Tools 4.3.1



/**
 * Location generated by hbm2java
 */
public class Location  implements java.io.Serializable {


     private Integer locId;
     private String locName;
     private String roadNo;
     private String block;
     private String houseNo;
     private String plotNo;
     private String flatNo;

    public Location() {
    }

    public Location(String locName, String roadNo, String block, String houseNo, String plotNo, String flatNo) {
       this.locName = locName;
       this.roadNo = roadNo;
       this.block = block;
       this.houseNo = houseNo;
       this.plotNo = plotNo;
       this.flatNo = flatNo;
    }
   
    public Integer getLocId() {
        return this.locId;
    }
    
    public void setLocId(Integer locId) {
        this.locId = locId;
    }
    public String getLocName() {
        return this.locName;
    }
    
    public void setLocName(String locName) {
        this.locName = locName;
    }
    public String getRoadNo() {
        return this.roadNo;
    }
    
    public void setRoadNo(String roadNo) {
        this.roadNo = roadNo;
    }
    public String getBlock() {
        return this.block;
    }
    
    public void setBlock(String block) {
        this.block = block;
    }
    public String getHouseNo() {
        return this.houseNo;
    }
    
    public void setHouseNo(String houseNo) {
        this.houseNo = houseNo;
    }
    public String getPlotNo() {
        return this.plotNo;
    }
    
    public void setPlotNo(String plotNo) {
        this.plotNo = plotNo;
    }
    public String getFlatNo() {
        return this.flatNo;
    }
    
    public void setFlatNo(String flatNo) {
        this.flatNo = flatNo;
    }




}


